# Generated by Django 5.0 on 2023-12-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('weight_class', models.CharField(choices=[('Atomweight', 'Atomweight'), ('Flyweight', 'Flyweight'), ('Bantamweight', 'Bantamweight'), ('Featherweight', 'Featherweight'), ('Lightweight', 'Lightweight'), ('Welterweight', 'Welterweight'), ('Middleweight', 'Middleweight'), ('Light Heavyweight', 'Light Heavyweight'), ('Heavyweight', 'Heavyweight'), ('Catch weight', 'Catch Weight')], max_length=100)),
                ('height', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('stance', models.CharField(choices=[('Orthodox', 'Orthodox'), ('Southpaw', 'Southpaw'), ('Switch', 'Switch'), ('Open Stance', 'Open Stance'), ('Side Stance', 'Side Stance'), ('Square Stance', 'Square Stance')], default='Orthodox', max_length=100, null=True)),
                ('dob', models.DateField(default=None, null=True)),
                ('api_link', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
