# Generated by Django 5.0 on 2023-12-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='nick_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
