# Generated by Django 5.0 on 2023-12-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0003_rename_api_link_fighter_data_api_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='nick_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
