# Generated by Django 5.0 on 2023-12-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0005_alter_fighter_stance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
