# Generated by Django 5.0 on 2023-12-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0006_rename_dob_fighter_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='stance',
            field=models.CharField(choices=[('N\\/A', 'Na'), ('Orthodox', 'Orthodox'), ('Southpaw', 'Southpaw'), ('Switch', 'Switch'), ('Open Stance', 'Open Stance'), ('Side Stance', 'Side Stance'), ('Square Stance', 'Square Stance')], default='N\\/A', max_length=100, null=True),
        ),
    ]
