# Generated by Django 5.0 on 2023-12-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0007_alter_fighter_stance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(choices=[('Atomweight', 'Atomweight'), ('Strawweight', 'Strawweight'), ('Flyweight', 'Flyweight'), ('Bantamweight', 'Bantamweight'), ('Featherweight', 'Featherweight'), ('Lightweight', 'Lightweight'), ('Welterweight', 'Welterweight'), ('Middleweight', 'Middleweight'), ('Light Heavyweight', 'Light Heavyweight'), ('Heavyweight', 'Heavyweight'), ('Catch weight', 'Catch Weight')], max_length=100),
        ),
    ]
