# Generated by Django 5.0 on 2023-12-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0011_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='head_movement',
            field=models.IntegerField(choices=[(0, 'Untested')], default=0),
        ),
    ]
