# Generated by Django 5.0 on 2023-12-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0012_alter_assessment_head_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='aggression',
            field=models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chinny',
            field=models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='desire_to_win',
            field=models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='gas_tank',
            field=models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='grappling_defense',
            field=models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='grappling_offense',
            field=models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='striking',
            field=models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='head_movement',
            field=models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=0),
        ),
    ]
