# Generated by Django 5.0 on 2023-12-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0013_assessment_aggression_assessment_chinny_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('tag', models.IntegerField(choices=[(0, 'Untested'), (1, 'Negative'), (2, 'Neutral'), (3, 'Positive')], default=2)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.assessment')),
            ],
        ),
    ]
