# Generated by Django 5.0 on 2023-12-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0014_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='note',
            name='createdAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
