# Generated by Django 5.0 on 2023-12-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0017_note2_fightevent_matchup_assessmentnote_matchupnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightevent',
            name='link',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fightevent',
            name='location',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
