# Generated by Django 5.0 on 2023-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0018_fightevent_link_fightevent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='rounds',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
