# Generated by Django 5.0 on 2023-12-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0019_matchup_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='data_api_link',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
