# Generated by Django 5.0 on 2023-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0020_alter_fighter_data_api_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='middle_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
