# Generated by Django 5.0 on 2023-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0021_fighter_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='data_api_link',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='middle_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
