# Generated by Django 5.0 on 2023-12-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0023_matchup_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='data_api_link',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='img_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='stance',
            field=models.CharField(blank=True, choices=[('N\\/A', 'Na'), ('Orthodox', 'Orthodox'), ('Southpaw', 'Southpaw'), ('Switch', 'Switch'), ('Open Stance', 'Open Stance'), ('Side Stance', 'Side Stance'), ('Square Stance', 'Square Stance')], default='N\\/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fightevent',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fightevent',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='result',
            field=models.CharField(blank=True, choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Draw', 'Draw'), ('No Contest', 'No Contest'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed'), ('Upcoming', 'Upcoming'), ('N/A', 'Na')], default='N/A', max_length=256, null=True),
        ),
    ]
