# Generated by Django 5.0 on 2023-12-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0025_alter_fighter_date_of_birth_alter_matchup_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='isprelim',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
