# Generated by Django 5.0 on 2023-12-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0030_alter_fighter_weight_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='draws',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='losses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(choices=[('n/a', 'Na'), ('atomweight', 'Atomweight'), ('strawweight', 'Strawweight'), ('flyweight', 'Flyweight'), ('bantamweight', 'Bantamweight'), ('featherweight', 'Featherweight'), ('lightweight', 'Lightweight'), ('welterweight', 'Welterweight'), ('middleweight', 'Middleweight'), ('light heavyweight', 'Light Heavyweight'), ('heavyweight', 'Heavyweight'), ('catch weight', 'Catch Weight')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='weight_class',
            field=models.CharField(choices=[('n/a', 'Na'), ('atomweight', 'Atomweight'), ('strawweight', 'Strawweight'), ('flyweight', 'Flyweight'), ('bantamweight', 'Bantamweight'), ('featherweight', 'Featherweight'), ('lightweight', 'Lightweight'), ('welterweight', 'Welterweight'), ('middleweight', 'Middleweight'), ('light heavyweight', 'Light Heavyweight'), ('heavyweight', 'Heavyweight'), ('catch weight', 'Catch Weight')], default='n/a', max_length=100),
        ),
    ]
