# Generated by Django 5.0 on 2023-12-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0031_alter_fighter_draws_alter_fighter_losses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='nick_name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='stance',
            field=models.CharField(blank=True, choices=[('N/A', 'Na'), ('Orthodox', 'Orthodox'), ('Southpaw', 'Southpaw'), ('Switch', 'Switch'), ('Open Stance', 'Open Stance'), ('Side Stance', 'Side Stance'), ('Square Stance', 'Square Stance')], default='N/A', max_length=100, null=True),
        ),
    ]
