# Generated by Django 5.0 on 2023-12-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0032_alter_fighter_nick_name_alter_fighter_stance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='stance',
            field=models.CharField(blank=True, choices=[('n/a', 'Na'), ('orthodox', 'Orthodox'), ('southpaw', 'Southpaw'), ('switch', 'Switch'), ('open stance', 'Open Stance'), ('side stance', 'Side Stance'), ('square stance', 'Square Stance')], default='n/a', max_length=100, null=True),
        ),
    ]
