# Generated by Django 5.0 on 2023-12-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0033_alter_fighter_stance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='aggression',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='chinny',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='desire_to_win',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='gas_tank',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='grappling_defense',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='grappling_offense',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='head_movement',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='striking',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=2),
        ),
        migrations.AlterField(
            model_name='note2',
            name='tag',
            field=models.IntegerField(choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=2),
        ),
    ]
