# Generated by Django 5.0 on 2023-12-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0034_alter_assessment_aggression_alter_assessment_chinny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(choices=[('n/a', 'Na'), ('atomweight', 'Atomweight'), ('strawweight', 'Strawweight'), ('flyweight', 'Flyweight'), ('bantamweight', 'Bantamweight'), ('featherweight', 'Featherweight'), ('lightweight', 'Lightweight'), ('welterweight', 'Welterweight'), ('middleweight', 'Middleweight'), ('light_heavyweight', 'Light Heavyweight'), ('heavyweight', 'Heavyweight'), ('catch_weight', 'Catch Weight')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='weight_class',
            field=models.CharField(choices=[('n/a', 'Na'), ('atomweight', 'Atomweight'), ('strawweight', 'Strawweight'), ('flyweight', 'Flyweight'), ('bantamweight', 'Bantamweight'), ('featherweight', 'Featherweight'), ('lightweight', 'Lightweight'), ('welterweight', 'Welterweight'), ('middleweight', 'Middleweight'), ('light_heavyweight', 'Light Heavyweight'), ('heavyweight', 'Heavyweight'), ('catch_weight', 'Catch Weight')], default='n/a', max_length=100),
        ),
    ]
