# Generated by Django 5.0 on 2023-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0035_alter_fighter_weight_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='stance',
            field=models.CharField(blank=True, choices=[('n/a', 'Na'), ('orthodox', 'Orthodox'), ('southpaw', 'Southpaw'), ('switch', 'Switch'), ('open_stance', 'Open Stance'), ('side_stance', 'Side Stance'), ('square_stance', 'Square Stance')], default='n/a', max_length=100, null=True),
        ),
    ]
