# Generated by Django 5.0 on 2024-01-08 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0036_alter_fighter_stance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='assessment_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='MatchUpOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('Win', 'Fighter wins'), ('1.5 >= Rnds', 'Fight lasts more than 1.5 rounds'), ('Fight Does Not Go the Distance(Ends before all rounds are completed)', 'Does Not Go The Distance')], max_length=256)),
                ('likelihood', models.IntegerField(blank=True, choices=[(5, 'Very Unlikely'), (4, 'Somewhat Unlikely'), (3, 'Neutral'), (2, 'Likely'), (1, 'Very Likely')], default=1, null=True)),
                ('fighter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fighter')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.matchup')),
            ],
        ),
    ]
