# Generated by Django 5.0 on 2024-01-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0037_alter_fighter_assessment_id_matchupoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchupoutcome',
            name='likelihood',
            field=models.IntegerField(blank=True, choices=[(5, 'Very Unlikely'), (4, 'Somewhat Unlikely'), (3, 'Neutral'), (2, 'Likely'), (1, 'Very Likely'), (0, 'Not Predicted')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matchupoutcome',
            name='outcome',
            field=models.CharField(choices=[('Win', 'Fighter wins'), ('1.5 >= Rnds', 'Fight lasts more than 1.5 rounds'), ('No', 'Fight Does Not Go the Distance')], max_length=256),
        ),
    ]
