# Generated by Django 5.0 on 2024-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0038_alter_matchupoutcome_likelihood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupoutcome',
            name='justification',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
