# Generated by Django 5.0 on 2024-01-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0040_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupoutcome',
            name='isprediction',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='matchupoutcome',
            name='isresult',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
    ]
