# Generated by Django 5.0 on 2024-01-29 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0043_alter_matchupoutcome_is_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('method', models.CharField(choices=[('KO/TKO', 'Knockout or Technical Knockout'), ('Sub', 'Submission'), ('UD/SD/MD', 'Unanimous Decision/Split Decision/Majority Decision'), ('Draw', 'Draw'), ('NC', 'No Contest'), ('N/A', 'Not Available')], default='N/A', max_length=256)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.matchup')),
            ],
        ),
    ]
