# Generated by Django 5.0 on 2024-01-30 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0045_remove_matchupoutcome_is_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightoutcome',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='fightEvaluator.fighter'),
        ),
    ]
