# Generated by Django 5.0 on 2024-01-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0046_fightoutcome_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightoutcome',
            name='final_round',
            field=models.IntegerField(default=0),
        ),
    ]
