# Generated by Django 5.0 on 2024-02-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0047_fightoutcome_final_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupoutcome',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
