# Generated by Django 5.0 on 2024-02-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0049_alter_matchupoutcome_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchupoutcome',
            name='name',
        ),
    ]
