# Generated by Django 5.0 on 2024-02-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0053_alter_eventlikelihood_likelihood'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlikelihood',
            name='event_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='MatchUpPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.matchup')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.eventlikelihood')),
            ],
        ),
    ]
