# Generated by Django 5.0 on 2024-02-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0054_eventlikelihood_event_name_matchupprediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlikelihood',
            old_name='event_name',
            new_name='event_type',
        ),
    ]
