# Generated by Django 5.0 on 2024-02-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0057_matchupprediction_isgamble_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchUpPrediction',
        ),
    ]
