# Generated by Django 5.0 on 2024-02-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0058_delete_matchupprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchUpOutcome',
        ),
    ]
