# Generated by Django 5.0.4 on 2024-05-07 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0062_alter_prediction_iscorrect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightoutcome',
            name='matchup',
        ),
        migrations.AddField(
            model_name='matchup',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fightEvaluator.fightoutcome'),
        ),
    ]
