# Generated by Django 5.0.4 on 2024-05-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0063_remove_fightoutcome_matchup_matchup_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='outcome',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fightEvaluator.fightoutcome'),
        ),
    ]
