# Generated by Django 5.1.2 on 2024-10-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0066_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='watchlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fightEvaluator.watchlist'),
        ),
    ]
