# Generated by Django 5.1.2 on 2024-10-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0067_matchup_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='matchup',
            name='inWatchList',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
