# Generated by Django 5.1.2 on 2024-10-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0068_remove_matchup_watchlist_matchup_inwatchlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='inWatchList',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
