# Generated by Django 5.1.2 on 2024-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0069_alter_matchup_inwatchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='analysisComplete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
