# Generated by Django 5.1.2 on 2024-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0070_matchup_analysiscomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='fighter_a_references',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='fighter_b_references',
            field=models.IntegerField(default=0),
        ),
    ]
