# Generated by Django 5.1.2 on 2024-11-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0074_fighteventdatastate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fightevent'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='fighter_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fighter_a', to='fightEvaluator.fighter'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='fighter_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fighter_b', to='fightEvaluator.fighter'),
        ),
    ]
