# Generated by Django 5.1.2 on 2024-11-25 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0075_alter_matchup_event_alter_matchup_fighter_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='fighter_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fighter_a', to='fightEvaluator.fighter'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='fighter_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fighter_b', to='fightEvaluator.fighter'),
        ),
    ]
