# Generated by Django 5.1.2 on 2024-11-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0076_alter_matchup_fighter_a_alter_matchup_fighter_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchupnote',
            name='note2_ptr',
        ),
        migrations.RemoveField(
            model_name='matchupnote',
            name='owner',
        ),
        migrations.DeleteModel(
            name='AssessmentNote',
        ),
        migrations.DeleteModel(
            name='Note2',
        ),
        migrations.DeleteModel(
            name='MatchupNote',
        ),
    ]
