# Generated by Django 5.1.2 on 2024-11-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0077_remove_matchupnote_note2_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test0', models.IntegerField(default=1)),
            ],
        ),
    ]
