# Generated by Django 5.1.2 on 2024-11-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0078_teststate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestState',
        ),
    ]
