# Generated by Django 5.1.2 on 2025-01-01 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0082_alter_prediction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchUp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_class', models.CharField(choices=[('n/a', 'Na'), ('atomweight', 'Atomweight'), ('strawweight', 'Strawweight'), ('flyweight', 'Flyweight'), ('bantamweight', 'Bantamweight'), ('featherweight', 'Featherweight'), ('lightweight', 'Lightweight'), ('welterweight', 'Welterweight'), ('middleweight', 'Middleweight'), ('light_heavyweight', 'Light Heavyweight'), ('heavyweight', 'Heavyweight'), ('catch_weight', 'Catch Weight')], default='n/a', max_length=100)),
                ('rounds', models.IntegerField(default=3)),
                ('is_prelim', models.BooleanField(default=True)),
                ('in_watchlist', models.BooleanField(blank=True, default=False, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fightevent')),
                ('fighter_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fighterA', to='fightEvaluator.fighter')),
                ('fighter_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fighterB', to='fightEvaluator.fighter')),
            ],
        ),
    ]
