# Generated by Django 5.1.2 on 2025-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0084_matchup2_analysis_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup2',
            name='analysis_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchup2',
            name='in_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
