# Generated by Django 5.1.2 on 2025-01-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0085_alter_matchup2_analysis_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='assessment_id',
        ),
    ]
