# Generated by Django 5.1.2 on 2025-02-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0086_remove_fighter_assessment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fightevent',
            options={'ordering': ['-date']},
        ),
    ]
