# Generated by Django 5.1.2 on 2025-02-10 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0087_alter_fightevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fighter')),
                ('attributes', models.ManyToManyField(blank=True, default=None, to='fightEvaluator.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(3, 'POSITIVE'), (2, 'NEUTRAL'), (1, 'NEGATIVE'), (0, 'UNTESTED')], default=0)),
                ('value_label', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.attribute')),
            ],
        ),
    ]
