# Generated by Django 5.1.2 on 2025-02-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0088_attribute_assessment2_attributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment2',
            name='attributes',
            field=models.ManyToManyField(blank=True, default=None, to='fightEvaluator.attributevalue'),
        ),
    ]
