# Generated by Django 5.1.2 on 2025-02-10 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0089_alter_assessment2_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='assessment2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fightEvaluator.assessment2'),
        ),
    ]
