# Generated by Django 5.1.2 on 2025-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0090_note_assessment2'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
