# Generated by Django 5.1.2 on 2025-02-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0091_attributevalue_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['-order']},
        ),
    ]
