# Generated by Django 5.1.2 on 2025-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0092_alter_attributevalue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={},
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='order',
        ),
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
