# Generated by Django 5.1.2 on 2025-02-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0093_alter_attribute_options_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(blank=True, choices=[('fight_outcome', 'Fight Outcome'), ('probability', 'Probability')], default=None, max_length=128, null=True)),
                ('count', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=-1)),
            ],
        ),
    ]
