# Generated by Django 5.1.2 on 2025-02-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0094_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(max_length=128, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.CharField(blank=True, choices=[('fight_outcome', 'Fight Outcome'), ('probability', 'Probability'), ('general', 'General')], default=None, max_length=128, null=True),
        ),
    ]
