# Generated by Django 5.1.2 on 2025-02-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0095_alter_stat_name_alter_stat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
