# Generated by Django 5.1.2 on 2025-02-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0096_alter_stat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='label',
            field=models.CharField(default='', max_length=256),
        ),
    ]
