# Generated by Django 5.1.2 on 2025-02-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0097_stat_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='scheduled',
        ),
    ]
