# Generated by Django 5.1.2 on 2025-02-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0099_stat_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='fighter_a_references',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='fighter_b_references',
        ),
    ]
