# Generated by Django 5.1.2 on 2025-02-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0100_remove_matchup_fighter_a_references_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=72)),
                ('vin', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='MyVehicle',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fightEvaluator.vehicle')),
            ],
            bases=('fightEvaluator.vehicle',),
        ),
    ]
