# Generated by Django 5.1.2 on 2025-02-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0101_vehicle_myvehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyVehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
