# Generated by Django 5.1.2 on 2025-02-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0102_delete_myvehicle_delete_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('Win', 'Fighter wins'), ('Yes', 'Fight Goes the Distance'), ('No', 'Fight Does Not Go the Distance'), ('Rnds >= 0.5', 'Fight lasts more than 0.5 rounds'), ('Rnds >= 1.5', 'Fight lasts more than 1.5 rounds'), ('Rnds >= 2.5', 'Fight lasts more than 2.5 rounds'), ('Rnds >= 3.5', 'Fight lasts more than 3.5 rounds'), ('Rnds >= 4.5', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], max_length=128)),
                ('likelihood', models.IntegerField(choices=[(5, 'Very Unlikely'), (4, 'Somewhat Unlikely'), (3, 'Neutral'), (2, 'Likely'), (1, 'Very Likely'), (0, 'Not Predicted')], default=3)),
                ('justification', models.CharField(max_length=1024)),
                ('correct', models.BooleanField(default=False)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.matchup')),
            ],
        ),
        migrations.CreateModel(
            name='WinPrediction',
            fields=[
                ('prediction2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fightEvaluator.prediction2')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fighter')),
            ],
            bases=('fightEvaluator.prediction2',),
        ),
    ]
