# Generated by Django 5.1.2 on 2025-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0103_prediction2_winprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winprediction',
            name='prediction2_ptr',
        ),
        migrations.RemoveField(
            model_name='winprediction',
            name='fighter',
        ),
        migrations.AddField(
            model_name='prediction',
            name='event',
            field=models.CharField(blank=True, choices=[('Win', 'Fighter wins'), ('Yes', 'Fight Goes the Distance'), ('No', 'Fight Does Not Go the Distance'), ('Rnds >= 0.5', 'Fight lasts more than 0.5 rounds'), ('Rnds >= 1.5', 'Fight lasts more than 1.5 rounds'), ('Rnds >= 2.5', 'Fight lasts more than 2.5 rounds'), ('Rnds >= 3.5', 'Fight lasts more than 3.5 rounds'), ('Rnds >= 4.5', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='justification',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='likelihood',
            field=models.IntegerField(blank=True, choices=[(5, 'Very Unlikely'), (4, 'Somewhat Unlikely'), (3, 'Neutral'), (2, 'Likely'), (1, 'Very Likely'), (0, 'Not Predicted')], default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Prediction2',
        ),
        migrations.DeleteModel(
            name='WinPrediction',
        ),
    ]
