# Generated by Django 5.1.2 on 2025-02-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0105_remove_prediction_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('Win', 'Fighter wins'), ('Yes', 'Fight Goes the Distance'), ('No', 'Fight Does Not Go the Distance'), ('Rnds >= 0.5', 'Fight lasts more than 0.5 rounds'), ('Rnds >= 1.5', 'Fight lasts more than 1.5 rounds'), ('Rnds >= 2.5', 'Fight lasts more than 2.5 rounds'), ('Rnds >= 3.5', 'Fight lasts more than 3.5 rounds'), ('Rnds >= 4.5', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], max_length=256)),
                ('eventType', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('likelihood', models.IntegerField(blank=True, choices=[(5, 'Very Unlikely'), (4, 'Somewhat Unlikely'), (3, 'Neutral'), (2, 'Likely'), (1, 'Very Likely'), (0, 'Not Predicted')], default=0, null=True)),
                ('justification', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('fighter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fighter')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.matchup')),
            ],
        ),
    ]
