# Generated by Django 5.1.2 on 2025-02-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0106_prediction2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGamble', models.BooleanField(default=False)),
                ('isCorrect', models.BooleanField(blank=True, default=None, null=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.matchup')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.eventlikelihood')),
            ],
        ),
    ]
