# Generated by Django 5.1.2 on 2025-02-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0109_alter_pick_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='event',
            field=models.CharField(blank=True, choices=[('Win', 'Fighter wins'), ('Yes', 'Fight Goes the Distance'), ('No', 'Fight Does Not Go the Distance'), ('Rnds >= 0.5', 'Fight lasts more than 0.5 rounds'), ('Rnds >= 1.5', 'Fight lasts more than 1.5 rounds'), ('Rnds >= 2.5', 'Fight lasts more than 2.5 rounds'), ('Rnds >= 3.5', 'Fight lasts more than 3.5 rounds'), ('Rnds >= 4.5', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], default=None, max_length=256, null=True),
        ),
    ]
