# Generated by Django 5.1.2 on 2025-02-24 02:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0110_pick_event'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fighter',
            index=models.Index(django.db.models.functions.text.Concat('first_name', models.Value('-'), 'last_name', output_field=models.CharField()), name='name_index'),
        ),
    ]
