# Generated by Django 5.1.2 on 2025-02-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0111_fighter_name_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fighter',
            name='name_index',
        ),
    ]
