# Generated by Django 5.1.2 on 2025-02-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0113_fighter_name_index_fighter_full_name_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fighter',
            name='full_name_index',
        ),
    ]
