# Generated by Django 5.1.2 on 2025-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0114_remove_fighter_full_name_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fighter',
            index=models.Index(fields=['name_index'], name='full_name_index'),
        ),
    ]
