# Generated by Django 5.1.2 on 2025-02-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0118_alter_eventlikelihood_event_alter_odd_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlikelihood',
            name='event',
            field=models.CharField(choices=[('WIN', 'Fighter wins'), ('GOES_THE_DISTANCE', 'Fight Goes the Distance'), ('DOES_NOT_GO_THE_DISTANCE', 'Fight Does Not Go the Distance'), ('ROUNDS_GEQ_ZERO_AND_HALF', 'Fight lasts more than 0.5 rounds'), ('ROUNDS_GEQ_ONE_AND_HALF', 'Fight lasts more than 1.5 rounds'), ('ROUNDS_GEQ_TWO_AND_HALF', 'Fight lasts more than 2.5 rounds'), ('ROUNDS_GEQ_THREE_AND_HALF', 'Fight lasts more than 3.5 rounds'), ('ROUNDS_GEQ_FOUR_AND_HALF', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], max_length=256),
        ),
        migrations.AlterField(
            model_name='odd',
            name='event',
            field=models.CharField(choices=[('WIN', 'Fighter wins'), ('GOES_THE_DISTANCE', 'Fight Goes the Distance'), ('DOES_NOT_GO_THE_DISTANCE', 'Fight Does Not Go the Distance'), ('ROUNDS_GEQ_ZERO_AND_HALF', 'Fight lasts more than 0.5 rounds'), ('ROUNDS_GEQ_ONE_AND_HALF', 'Fight lasts more than 1.5 rounds'), ('ROUNDS_GEQ_TWO_AND_HALF', 'Fight lasts more than 2.5 rounds'), ('ROUNDS_GEQ_THREE_AND_HALF', 'Fight lasts more than 3.5 rounds'), ('ROUNDS_GEQ_FOUR_AND_HALF', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], max_length=256),
        ),
        migrations.AlterField(
            model_name='pick',
            name='event',
            field=models.CharField(blank=True, choices=[('WIN', 'Fighter wins'), ('GOES_THE_DISTANCE', 'Fight Goes the Distance'), ('DOES_NOT_GO_THE_DISTANCE', 'Fight Does Not Go the Distance'), ('ROUNDS_GEQ_ZERO_AND_HALF', 'Fight lasts more than 0.5 rounds'), ('ROUNDS_GEQ_ONE_AND_HALF', 'Fight lasts more than 1.5 rounds'), ('ROUNDS_GEQ_TWO_AND_HALF', 'Fight lasts more than 2.5 rounds'), ('ROUNDS_GEQ_THREE_AND_HALF', 'Fight lasts more than 3.5 rounds'), ('ROUNDS_GEQ_FOUR_AND_HALF', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prediction2',
            name='event',
            field=models.CharField(choices=[('WIN', 'Fighter wins'), ('GOES_THE_DISTANCE', 'Fight Goes the Distance'), ('DOES_NOT_GO_THE_DISTANCE', 'Fight Does Not Go the Distance'), ('ROUNDS_GEQ_ZERO_AND_HALF', 'Fight lasts more than 0.5 rounds'), ('ROUNDS_GEQ_ONE_AND_HALF', 'Fight lasts more than 1.5 rounds'), ('ROUNDS_GEQ_TWO_AND_HALF', 'Fight lasts more than 2.5 rounds'), ('ROUNDS_GEQ_THREE_AND_HALF', 'Fight lasts more than 3.5 rounds'), ('ROUNDS_GEQ_FOUR_AND_HALF', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], max_length=256),
        ),
    ]
