# Generated by Django 5.1.6 on 2025-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0119_alter_eventlikelihood_event_alter_odd_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='aggression',
            field=models.IntegerField(blank=True, choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='chinny',
            field=models.IntegerField(blank=True, choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='desire_to_win',
            field=models.IntegerField(blank=True, choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='gas_tank',
            field=models.IntegerField(blank=True, choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='grappling_defense',
            field=models.IntegerField(blank=True, choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='grappling_offense',
            field=models.IntegerField(blank=True, choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='head_movement',
            field=models.IntegerField(blank=True, choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='striking',
            field=models.IntegerField(blank=True, choices=[(0, 'untested'), (1, 'negative'), (2, 'neutral'), (3, 'positive')], default=0),
        ),
    ]
