# Generated by Django 5.1.6 on 2025-08-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0120_alter_assessment_aggression_alter_assessment_chinny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='fighter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fighter'),
        ),
    ]
