# Generated by Django 5.1.2 on 2025-08-19 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0121_alter_assessment_fighter'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictions', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0.0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fightevent')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyEventStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('events', models.IntegerField(default=0)),
                ('predictions', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
