# Generated by Django 5.1.2 on 2025-08-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0122_stataggregate_eventstat_monthlyeventstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatAggregate',
        ),
    ]
