# Generated by Django 5.1.2 on 2025-08-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0123_delete_stataggregate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyeventstats',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eventstat',
            name='ratio',
        ),
        migrations.AddConstraint(
            model_name='monthlyeventstats',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_year_month'),
        ),
    ]
