# Generated by Django 5.1.2 on 2025-08-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0124_alter_monthlyeventstats_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyeventstats',
            name='accuracy',
        ),
    ]
