# Generated by Django 5.1.2 on 2025-08-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0125_remove_monthlyeventstats_accuracy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_attribute_value'),
        ),
    ]
