# Generated by Django 5.1.2 on 2025-08-22 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0126_attributevalue_unique_attribute_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttribValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.assessment2')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.attributevalue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assessment', 'attribute_value'), name='unique_assessment_value')],
            },
        ),
    ]
