# Generated by Django 5.1.2 on 2025-08-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0127_assessmentattribvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment2',
            name='attributes',
        ),
    ]
