# Generated by Django 5.1.2 on 2025-08-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0128_remove_assessment2_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment2',
            name='attributes',
            field=models.ManyToManyField(blank=True, default=None, through='fightEvaluator.AssessmentAttribValue', to='fightEvaluator.attributevalue'),
        ),
    ]
