# Generated by Django 5.1.6 on 2025-08-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0129_assessment2_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentattribvalue',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='note',
            name='assessment2',
        ),
        migrations.RemoveField(
            model_name='assessmentattribvalue',
            name='attribute_value',
        ),
        migrations.DeleteModel(
            name='Assessment2',
        ),
        migrations.DeleteModel(
            name='AssessmentAttribValue',
        ),
    ]
