# Generated by Django 5.1.2 on 2025-08-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0129_assessment2_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='assessment2',
        ),
    ]
