# Generated by Django 5.1.2 on 2025-08-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0130_remove_note_assessment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment2',
            name='attributes',
        ),
    ]
