# Generated by Django 5.1.2 on 2025-08-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0131_remove_assessment2_attributes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentattribvalue',
            name='unique_assessment_value',
        ),
    ]
