# Generated by Django 5.1.2 on 2025-08-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0132_remove_assessmentattribvalue_unique_assessment_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentAttribValue',
        ),
    ]
