# Generated by Django 5.1.2 on 2025-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0134_assessmentattribvalue'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('matchup', 'event'), name='unique-matchup-event-pick'),
        ),
    ]
