# Generated by Django 5.1.2 on 2025-09-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0135_pick_unique_matchup_event_pick'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pick',
            name='unique-matchup-event-pick',
        ),
    ]
