# Generated by Django 5.1.2 on 2025-09-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0136_remove_pick_unique_matchup_event_pick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='matchup',
        ),
    ]
