# Generated by Django 5.1.2 on 2025-09-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0137_remove_pick_matchup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pick',
        ),
    ]
