# Generated by Django 5.1.2 on 2025-09-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0138_delete_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, choices=[('WIN', 'Fighter wins'), ('GOES_THE_DISTANCE', 'Fight Goes the Distance'), ('DOES_NOT_GO_THE_DISTANCE', 'Fight Does Not Go the Distance'), ('ROUNDS_GEQ_ZERO_AND_HALF', 'Fight lasts more than 0.5 rounds'), ('ROUNDS_GEQ_ONE_AND_HALF', 'Fight lasts more than 1.5 rounds'), ('ROUNDS_GEQ_TWO_AND_HALF', 'Fight lasts more than 2.5 rounds'), ('ROUNDS_GEQ_THREE_AND_HALF', 'Fight lasts more than 3.5 rounds'), ('ROUNDS_GEQ_FOUR_AND_HALF', 'Fight lasts more than 4.5 rounds'), ('NA', 'Not Available')], default=None, max_length=256, null=True)),
                ('isGamble', models.BooleanField(blank=True, default=False)),
                ('isCorrect', models.BooleanField(blank=True, default=None, null=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.matchup', unique=True)),
                ('prediction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fightEvaluator.prediction2')),
            ],
        ),
    ]
