# Generated by Django 5.1.2 on 2025-09-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0139_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='fighter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.fighter'),
        ),
    ]
