# Generated by Django 5.1.2 on 2025-09-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0140_pick_fighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlikelihood',
            name='justification',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
