# Generated by Django 5.2.8 on 2026-04-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0145_alter_prediction_prediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchUp2',
        ),
    ]
