# Generated by Django 5.2.15 on 2026-09-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightEvaluator', '0146_delete_matchup2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='matchup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fightEvaluator.matchup'),
        ),
    ]
