from .index import *
from .assessment import *
from .matchups import *
from .note import *
from .fighter import *
from .prediction import *
from .profit import *
from .test_view import *
from .vue_index import *
from .scrapy_view import *